name: snpsift_annotate
description: |
  Add INFO fields from one VCF to another VCF. For example, add public annotations
  from ClinVar to the dataset being analyzed.
keywords:
  - vcf
  - annotation
tools:
  - snpeff:
      description: |
        SnpEff is a variant annotation and effect prediction tool.
        It annotates and predicts the effects of genetic variants on genes and proteins (such as amino acid changes).
        SnpSift is included with the SnpEff installation and is a toolbox for filtering and
        manipulating annotated files.
      homepage: https://pcingola.github.io/SnpEff/
      documentation: https://pcingola.github.io/SnpEff/se_introduction/
      licence: ["MIT"]
input:
  - vcf:
      type: file
      description: VCF file to annotate.
  - annotations_vcf:
      type: files
      description: |
        Tuple containing firstly the VCF file with INFO fields to transfer over, and
        secondly its index.
  - fields:
      type: string
      description: Comma-separated list of INFO fields to transfer.
output:
  - vcf:
      type: file
      description: Annotated VCF.
      pattern: "*.snpsift.{vcf}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@maxulysse"
  - "@lvclark"
