name: call_variants_single
description: |
  Second step in variant calling on individual samples.
  Processes one sample at a time.  The input is a single tuple out of the three
  output by make_examples_single. Note that params.deepvar_model needs to be set
  to WES or WGS.
Tools:
  - deepvariant:
      description: |
        DeepVariant is a deep learning-based variant caller that takes aligned
        reads (in BAM or CRAM format), produces pileup image tensors from them,
        classifies each tensor using a convolutional neural network, and finally
        reports the results in a standard VCF or gVCF file.
      homepage: https://github.com/google/deepvariant
      doi: 10.1101/2021.04.05.438434
      license: ["BSD 3-Clause"]
input:
  - meta:
      type: map
      description: |
        Metadata map with "id" giving sample ID.
  - me_tfrecord:
      type: path
      description: List of make_examples tfrecord files.
  - gvcf_tfrecord:
      type: path
      description: |
        List of gvcf tfrecord files. It is not used by this process but is
        passed through to be used by postprocess_variants.
  - example_info:
      type: path
      description: JSON files containing model information, generated by make_examples.
output:
  - meta:
      type: value
      description: Meta map that was input.
  - cv_tfrecord:
      type: path
      description: List of call_variants tfrecord files.
      pattern: "call_variants*.tfrecord.gz"
  - gvcf_tfrecord:
      type: path
      description: List of gvcf tfrecord files.
      pattern: "gvcf*.tfrecord-*-of-*.gz"
authors:
  - "@lvclark"
