process BCFTOOLS_CONCAT {
    container = "https://depot.galaxyproject.org/singularity/bcftools:1.17--haef29d1_0"
    shell = ['/bin/bash', '-euo', 'pipefail']

    input:
        path(vcfs)     // List of VCFs
        val(vcfstring) // For ordering vCFs. Generated by FILEORDER.
    output: path(outvcf), emit: vcf

    exec:
    prefix = file(params.vcf).simpleName
    outvcf = "${prefix}.concat.vcf"

    script:
    """
bcftools concat --threads $task.cpus --output $outvcf -Oz $vcfstring
    """
}
