process BCFTOOLS_CONCAT {
    container "https://depot.galaxyproject.org/singularity/bcftools:1.17--haef29d1_0"
    shell '/bin/bash', '-euo', 'pipefail'
    label 'process_single'

    input:
        path(vcfs)     // List of VCFs
        val(vcfstring) // For ordering vCFs. Generated by FILEORDER.
        val(prefix)
    output: path(outvcf), emit: vcf

    exec:
    outvcf = "${prefix}.concat.vcf.gz"

    script:
    """
bcftools concat --threads $task.cpus --output $outvcf -Oz $vcfstring
    """
}
